services:
  wordpress:
    build:
      context: .
      dockerfile: wp.Dockerfile
    ports:
      - 8080:80
    depends_on:
      - mysql
    #starts mysql container before wordpress
  mysql:
    build:
      context: .
      dockerfile: mysql.Dockerfile

